### ISSUE TITLE
Custom code location on server

### ISSUE THREAD

**Issue by bsommerhalder** [juliushaertl/theming_customcss#12]
I broke my NC instance with some bad CSS code using this app (my bad), and I cannot access the Custom CSS module via the web interface to correct it.

Where does the code that is entered in the Custom CSS field "live" on the server? I would like to remove the offending line that I added, if you could please point me to the path to where this information is stored. Thank you in advance.

**Comment by blackcrack** [comment]
you should download the orginal tar.gz and overwrite the orginal css files,
then, could you use http://www.blackysgate.de/files/folder-root/nextcloud/
as example, then could you make a own folder and start up to create step by step a theme.
my theme is a NC 16.0.X theme and have started at nc 14 or something..
but i guess it is so or so  a "good" example for building an own theme.
extract the tar.gz in a own folder "/themes/nextrealtime" and add the "folder-theme-name"entry in config.php, deactivate "Theming" from NC as admin/root and the theme should so far works..

and if you make a own folder, can you make a css-folder, create a server.css
and can make for earch application an own app.css and can link it in/import
into the server.css with 
```
@import 'style.css';
@import 'app.css';
``` 
like i have done it ..

the App "Themes" must be deactivated, for to be the customcss well running .
Therefore must you know, nativ is the themes supported (since owncloud), 
the App "Themes" was added in later versions of NextCloud 
because this is the app "Themes" a bit a disturber for the "real" Themes in NC.

and happy css hacking :) 

best regards
Blacky

**Comment by juliushaertl** [comment]
@blackcrack What you explain has nothing to do with the theming_customcss app, so I'll hide that comment to keep the discussion clean.

@bsommerhalder You can just remove the saved custom css by running:

php occ config:app:delete theming_customcss customcss

That will delete all stored css rules from the app. Make sure to hard refresh your browser afterwards.

**Comment by blackcrack** [comment]
:+1:
