### ISSUE TITLE
user/group-dependance [feature request]

### ISSUE THREAD

**Issue by yasuoiwakura** [juliushaertl/theming_customcss#13]
great tool, appreciate it!

i think it could make sense to dedicate custom CSS-Sets for certain users or groups.
e.g. red color for admins, hide "complicated" functions from non-techy-users, etc. etc.

**Comment by blackcrack** [comment]
Hi,

unnessary \*imho*, because a Theme is for customizing the look and feel for the whole Cloud
and would to make work to support also for a User-accound or a Group-accaunt.
A theme for the Nextcloud and this Support Custom themecss-app is work enough..
but if you want bring in patches in form of Upgrades and  improvement, 
i'm guess , you're welcome.
but i can't speak for Julius.

best regards
Blacky

**Comment by juliushaertl** [comment]
Yes, I think that is quite a specific use case and in that case you could simply implement a custom app for this that loads stylesheets based on the user id or group membership.
