### ISSUE TITLE
Not Limiting Gropus

### ISSUE THREAD

**Issue by henriquescvs** [juliushaertl/theming_customcss#26]
![image](https://user-images.githubusercontent.com/93736811/141027825-f2c99892-a7e9-438a-bbaa-357d91ed8318.png)

As you can see, is group limited, however, the custom CSS is action in all groups, as Admin.

**Comment by LazyCoderOZ** [comment]
Hi,
I am having the same problem with limiting to groups. 
Expected behavior is the css modification is limited to the listed groups
Actual behavior is it limits for all groups.
Nextcloud version is 24.0.3
Running on docker host, mariadb version
```
mysql  Ver 15.1 Distrib 10.5.16-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
PHP
```
HP 8.0.21 (cli) (built: Jul 12 2022 08:53:27) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.21, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.21, Copyright (c), by Zend Technologies
```
The customcss version as retrieved from mariadb
```
| theming_customcss | installed_version | 1.11.0
```

The screenshots below is the behavior of the nextcloud instance without the app enabled
![Screenshot from 2022-07-30 16-00-48](https://user-images.githubusercontent.com/10446258/181879434-01d75b74-743c-4442-b1c7-d2f1e5dc923c.png)

![Screenshot from 2022-07-30 16-01-08](https://user-images.githubusercontent.com/10446258/181879452-78be4b79-9253-4b5b-9dfd-ec3b54925c46.png)

The next screenshot details the css modifications done, the modifications are below:
```
#open-reasons-use-nextcloud-pdf {display:none;} /*Hide the reasons to use nextcloud banner */
#contactsmenu {display: none;} /* Hide the contacts menu from the users */
#app-content-files .action-delete-container {display: none} Remove the delete container from the 3 dot menu next to file*/
#richdocuments-actions .icon-download { display: none} /* Remove the download option for a document in 3 dots menu in collabora header*/
#app-content-files .action-download-container {display: none}  /*Remove download from the 3 dot menu on the right side of the file */
#app-content-files .action.download.permanent {display: none} /* Remove the download option form the Actions menu*/
#viewer .action-item__menutoggle {display: none} /*Remove 3 dot menu from the header of the pdf viewer*/
#app-content-files .action-edit.with.collabora.online.development.edition-container {display: none} /*Remove Edit with Collabora from 3 dot menu to right of file*/
#app-content-files .action.delete.permanent {display: none}  /*Remove the delete file from the Action menu */
/* do not show the readme.md file in the list */
tr[data-file*="Readme.md"] {
display: none !important;
}
/* hide the edit menu of the readme.md */
.menubar.autohide{
display: none !important;
}
/* make the "editor field" not clickable */
#editor-wrapper div.ProseMirror[contenteditable="true"], 
#editor-wrapper div.ProseMirror[contenteditable="false"] {
pointer-events: none!important;
}
/* hide the workspace */
#rich-workspace #editor-container {
display: none !important;
}
```
![Screenshot from 2022-07-30 16-01-59](https://user-images.githubusercontent.com/10446258/181879546-e0e5f6c2-7699-4a35-8ef3-bb10b5f4e499.png)

The next screenshot shows my 2 users and their respective groups

![Screenshot from 2022-07-30 16-02-58](https://user-images.githubusercontent.com/10446258/181879580-f90c5c18-7d48-4f54-b416-52b2809583ab.png)

We now limit the custom css app to the cert_III group only

![Screenshot from 2022-07-30 16-18-02](https://user-images.githubusercontent.com/10446258/181879639-f0106ab6-ceb9-4275-ba1e-6544738c4455.png)

For the student, behavior is as expected as per the 2 following screenshots

![Screenshot from 2022-07-30 16-37-44](https://user-images.githubusercontent.com/10446258/181879663-35f4cf18-e6e6-4f4e-9bb5-861987e2d1aa.png)


![Screenshot from 2022-07-30 16-38-00](https://user-images.githubusercontent.com/10446258/181879679-a1192cd3-9d17-4216-8418-8c19bcbfc979.png)

For the admin member, expected behavior should be no change to the menu system, however the admin is now restricted as well
![Screenshot from 2022-07-30 16-38-43](https://user-images.githubusercontent.com/10446258/181879715-934b9954-922a-49d0-9e87-543c7f680d19.png)


![Screenshot from 2022-07-30 16-38-54](https://user-images.githubusercontent.com/10446258/181879726-50f26001-fdb0-45a4-9300-3f3c7791b038.png)

In addition, the custom css settings in the admin account for the nextcloud instance is now missing altogether

![Screenshot from 2022-07-30 16-53-53](https://user-images.githubusercontent.com/10446258/181879789-426a6e5b-6be7-4e57-82a3-0ece2069fa06.png)

Expected behavior should be no change to the admin settings for custom css
Actual behavior is custom css settings now missing.
Any help that you could provide to assist me in overcoming these issues would be fantastic.
Regards,
LazycoderOZ

**Comment by juliushaertl** [comment]
Seems like the listener in https://github.com/juliushaertl/theming_customcss/blob/master/lib/AppInfo/Application.php#L45 is always registered independent of if the app is enabled for the group.

**Comment by LazyCoderOZ** [comment]
The app now will work correctly with groups, if admin is not one of the groups which the app is restricted to, the configuration does not appear in the theming menu under the Nextcloud settings. 
The fix I have found for this, is when you wish to modify the css, just add admin to the restricted groups, do your editing, make sure it works and then remove admin again from the restricted groups.
The admin will then be able to do all actions on the files while the users in the restricted list will be subjected to your modified css.
