### ISSUE TITLE
Change text color on login page

### ISSUE THREAD

**Issue by F1iX** [juliushaertl/theming_customcss#7]
Hi Julius,
how can I change the text color of the Nextcloud login page?
With
```
#body-login {
	background: red;
        color: white;
}
```
indeed the background gets red, but the text won't get white...
Thanks!

**Comment by juliushaertl** [comment]
You probably need to adjust more elements, since the font color is set on some child elements as well. I'd recommend to inspect elements where your rules do not apply with the browser developer tools and extend the css according to that.

For further help, please head over to help.nextcloud.com since github is only used to track bugs and feature requests.
